spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/translation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

auth:
  admin:
    username: admin
    password: "S3cureAdm!nP@ss123"  # Strong password for production

jwt:
  secret: "pK8nX#mY2$vL9qR5tF3*hJ7bN4wA6cE1gU8sZ0pD"  # 256-bit secure key
  expiration: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    com.translation: DEBUG
